version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - app-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - app-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: votacao
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./api/bd/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: rodrigo2005/assembleia-votacao:latest
    container_name: assembleia-votacao
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - db
      - zookeeper
      - kafka 

networks: 
  app-network:
   
